
export const icons = {
    groups: [
        {
            label: '方向指示类',
            icons: [
                'ArrowUpOutlined',
                'ArrowDownOutlined',
                'ArrowLeftOutlined',
                'ArrowRightOutlined',
                'UpOutlined',
                'DownOutlined',
                'LeftOutlined',
                'RightOutlined',
                'UpCircleOutlined',
                'DownCircleOutlined',
                'LeftCircleOutlined',
                'RightCircleOutlined',
                'UpSquareOutlined',
                'DownSquareOutlined',
                'LeftSquareOutlined',
                'RightSquareOutlined',
                'CaretUpOutlined',
                'CaretDownOutlined',
                'CaretLeftOutlined',
                'CaretRightOutlined',
                'DoubleLeftOutlined',
                'DoubleRightOutlined',
                'BackwardOutlined',
                'ForwardOutlined',
                'FastBackwardOutlined',
                'FastForwardOutlined',
                'StepBackwardOutlined',
                'StepForwardOutlined',
                'VerticalAlignTopOutlined',
                'VerticalAlignMiddleOutlined',
                'VerticalAlignBottomOutlined',
                'VerticalLeftOutlined',
                'VerticalRightOutlined',
                'ToTopOutlined',
                'ArrowsAltOutlined',
                'SwapOutlined',
                'SwapLeftOutlined',
                'SwapRightOutlined',
                'EnterOutlined',
                'ShrinkOutlined',
                'ExpandOutlined',
                'ExpandAltOutlined',
                'CompressOutlined',
            ]
        },
        {
            label: '编辑类',
            icons: [
                'EditOutlined',
                'FormOutlined',
                'DeleteOutlined',
                'DeleteColumnOutlined',
                'DeleteRowOutlined',
                'InsertRowAboveOutlined',
                'InsertRowBelowOutlined',
                'InsertRowLeftOutlined',
                'InsertRowRightOutlined',
                'CopyOutlined',
                'SaveOutlined',
                'ExportOutlined',
                'ImportOutlined',
                'UndoOutlined',
                'RedoOutlined',
                'FormatPainterOutlined',
                'ScissorOutlined',
                'DragOutlined',
                'HolderOutlined',
                'CodeOutlined',
                'ConsoleSqlOutlined',
                'PullRequestOutlined',
                'SplitCellsOutlined',
                'MergeCellsOutlined',
                'MergeOutlined',
                'UngroupOutlined',
            ]
        },
        {
            label: '提示状态类',
            icons: [
                'InfoCircleOutlined',
                'InfoOutlined',
                'CheckCircleOutlined',
                'CheckOutlined',
                'CheckSquareOutlined',
                'ExclamationCircleOutlined',
                'ExclamationOutlined',
                'WarningOutlined',
                'CloseCircleOutlined',
                'CloseOutlined',
                'CloseSquareOutlined',
                'QuestionCircleOutlined',
                'QuestionOutlined',
                'StopOutlined',
                'LoadingOutlined',
                'Loading3QuartersOutlined',
                'ClockCircleOutlined',
                'HistoryOutlined',
                'SyncOutlined',
                'ReloadOutlined',
                'FireOutlined',
            ]
        },
        {
            label: '通用符号类',
            icons: [
                'HeartOutlined',
                'StarOutlined',
                'LikeOutlined',
                'DislikeOutlined',
                'TagOutlined',
                'TagsOutlined',

                'BellOutlined',
                'EyeOutlined',
                'EyeInvisibleOutlined',
                'LockOutlined',
                'UnlockOutlined',
                'SecurityScanOutlined',

                'SafetyCertificateOutlined',
                'SafetyOutlined',
                'HomeOutlined',
                'AppstoreOutlined',
                'AppstoreAddOutlined',
                'BlockOutlined',

                'LayoutOutlined',
                'FullscreenOutlined',
                'FullscreenExitOutlined',
                'LinkOutlined',
                'PaperClipOutlined',
                'PictureOutlined',

                'VideoCameraOutlined',
                'VideoCameraAddOutlined',
                'AudioOutlined',
                'AudioMutedOutlined',
                'SoundOutlined',
                'MutedOutlined',

                'FilterOutlined',
                'SearchOutlined',
                'ZoomInOutlined',
                'ZoomOutOutlined',
                'EnvironmentOutlined',
                'PushpinOutlined',

                'CompassOutlined',
                'FlagOutlined',
                'RadiusUpleftOutlined',
                'RadiusUprightOutlined',
                'RadiusBottomleftOutlined',
                'RadiusBottomrightOutlined',

                'RadiusSettingOutlined',
                'ShareAltOutlined',
                'QrcodeOutlined',
                'BarcodeOutlined',
                'PrinterOutlined',
                'TranslationOutlined',
                'MacCommandOutlined',
            ]
        },
        {
            label: '文件文档类',
            icons: [
                'FileOutlined',
                'FilePdfOutlined',
                'FileWordOutlined',
                'FileExcelOutlined',
                'FilePptOutlined',
                'FileMarkdownOutlined',

                'FileImageOutlined',
                'FileZipOutlined',
                'FileTextOutlined',
                'FileUnknownOutlined',
                'FileExclamationOutlined',
                'FileDoneOutlined',

                'FileSearchOutlined',
                'FileProtectOutlined',
                'FileSyncOutlined',
                'FileAddOutlined',
                'FileJpgOutlined',
                'FileGifOutlined',

                'SnippetsOutlined',
                'BookOutlined',
                'ReadOutlined',
                'UnorderedListOutlined',
                'OrderedListOutlined',
                'MailOutlined',

                'InboxOutlined',
                'SolutionOutlined',
            ]
        },
        {
            label: '数据图表类',
            icons: [
                'AreaChartOutlined',
                'LineChartOutlined',
                'BarChartOutlined',
                'PieChartOutlined',
                'DotChartOutlined',
                'RadarChartOutlined',
                'HeatMapOutlined',
                'NumberOutlined',
                'PercentageOutlined',
                'RiseOutlined',
                'FallOutlined',
                'FundOutlined',
                'FundViewOutlined',
                'FundProjectionScreenOutlined',
                'StockOutlined',
                'DollarOutlined',
                'DollarCircleOutlined',
                'EuroOutlined',
                'EuroCircleOutlined',
                'PoundOutlined',
                'PoundCircleOutlined',
                'WalletOutlined',
                'MoneyCollectOutlined',
                'BankOutlined',
                'PayCircleOutlined',
                'InsuranceOutlined',
                'ReconciliationOutlined',
                'AuditOutlined',
                'CalculatorOutlined',
                'TableOutlined',
                'BorderVerticleOutlined',
                'BorderHorizontalOutlined',
                'BorderLeftOutlined',
                'BorderRightOutlined',
                'BorderTopOutlined',
                'BorderBottomOutlined',
                'BorderOutlined',
                'BorderInnerOutlined',
                'BorderOuterOutlined',
                'BorderlessTableOutlined',
            ]
        },
        {
            label: '用户组织类',
            icons: [
                'UserOutlined',
                'UserAddOutlined',
                'UserDeleteOutlined',
                'UserSwitchOutlined',
                'TeamOutlined',
                'UsergroupAddOutlined',
                'UsergroupDeleteOutlined',
                'ContactsOutlined',
                'CustomerServiceOutlined',
                'ManOutlined',
                'WomanOutlined',
                'IdcardOutlined',
                'VerifiedOutlined',
                'CrownOutlined',
                'TrophyOutlined',
                'GiftOutlined',
                'RedEnvelopeOutlined',
                'ApartmentOutlined',
                'DeploymentUnitOutlined',
                'ClusterOutlined',
                'ProjectOutlined',
                'BranchesOutlined',
                'SubnodeOutlined',
                'NodeCollapseOutlined',
                'NodeExpandOutlined',
                'NodeIndexOutlined',
                'PartitionOutlined',
                'CalendarOutlined',
                'ScheduleOutlined',
            ]
        },
        {
            label: '设备硬件类',
            icons: [
                'DesktopOutlined',
                'LaptopOutlined',
                'MobileOutlined',
                'PhoneOutlined',
                'TabletOutlined',
                'CloudOutlined',

                'CloudServerOutlined',
                'CloudUploadOutlined',
                'CloudDownloadOutlined',
                'CloudSyncOutlined',
                'DatabaseOutlined',
                'HddOutlined',

                'ContainerOutlined',
                'WifiOutlined',
                'UsbOutlined',
                'CarOutlined',
                'TruckOutlined',
                'ToolOutlined',

                'MedicineBoxOutlined',
                'BoxPlotOutlined',
                'CameraOutlined',
                'RobotOutlined',
                'RocketOutlined',
                'ExperimentOutlined',
                'BugOutlined',
                'BuildOutlined',
                'ShopOutlined',
                'ShoppingOutlined',
                'ShoppingCartOutlined',
                'ProductOutlined',
                'DashboardOutlined',
                'ControlOutlined',
                'SlidersOutlined',
                'SettingOutlined',
                'BulbOutlined',
                'PoweroffOutlined',
                'SunOutlined',
                'MoonOutlined',
            ]
        },
        {
            label: '品牌标识类',
            icons: [
                'AlibabaOutlined',
                'AlipayCircleOutlined',
                'AlipayOutlined',
                'TaobaoCircleOutlined',
                'TaobaoOutlined',
                'DingtalkOutlined',

                'DingdingOutlined',
                'WechatOutlined',
                'WechatWorkOutlined',
                'QqOutlined',
                'WeiboCircleOutlined',
                'WeiboOutlined',

                'WeiboSquareOutlined',
                'ZhihuOutlined',
                'BaiduOutlined',
                'YuqueOutlined',
                'TikTokOutlined',
                'AmazonOutlined',

                'AppleOutlined',
                'AndroidOutlined',
                'ChromeOutlined',
                'IeOutlined',
                'GithubOutlined',
                'GitlabOutlined',

                'Html5Outlined',
                'JavaScriptOutlined',
                'PythonOutlined',
                'JavaOutlined',
                'RubyOutlined',
                'GoogleOutlined',

                'GooglePlusOutlined',
                'FacebookOutlined',
                'TwitterOutlined',
                'XOutlined',
                'InstagramOutlined',
                'LinkedinOutlined',

                'YoutubeOutlined',
                'YahooOutlined',
                'SkypeOutlined',
                'SlackOutlined',
                'SlackSquareOutlined',
                'MediumOutlined',

                'MediumWorkmarkOutlined',
                'RedditOutlined',
                'WhatsAppOutlined',
                'DiscordOutlined',
                'SpotifyOutlined',
                'DropboxOutlined',

                'BehanceOutlined',
                'BehanceSquareOutlined',
                'DribbbleOutlined',
                'DribbbleSquareOutlined',
                'SketchOutlined',
                'PinterestOutlined',

                'TwitchOutlined',
                'WindowsOutlined',
                'LinuxOutlined',
                'CodepenOutlined',
                'CodeSandboxOutlined',
                'AntDesignOutlined',

                'AntCloudOutlined',
                'AliyunOutlined',
                'CiCircleOutlined',
                'CiOutlined',
                'TrademarkCircleOutlined',
                'TrademarkOutlined',

                'CopyrightCircleOutlined',
                'CopyrightOutlined',
                'OpenAIOutlined',
                'HarmonyOSOutlined',
                'DotNetOutlined',
                'AliwangwangOutlined',
                'DockerOutlined',
                'KubernetesOutlined',
            ]
        },
        {
            label: '其他类',
            icons: [
                'ThunderboltOutlined',
                'FontSizeOutlined',
                'FontColorsOutlined',
                'BoldOutlined',
                'ItalicOutlined',
                'UnderlineOutlined',
                'StrikethroughOutlined',
                'HighlightOutlined',
                'SmallDashOutlined',
                'DashOutlined',
                'ColumnHeightOutlined',
                'ColumnWidthOutlined',
                'LineHeightOutlined',
                'AlignCenterOutlined',
                'AlignLeftOutlined',
                'AlignRightOutlined',
                'AimOutlined',
                'RotateLeftOutlined',
                'RotateRightOutlined',
                'MessageOutlined',
                'CommentOutlined',
                'ClearOutlined',
                'BgColorsOutlined',
                'EllipsisOutlined',
                'MonitorOutlined',
                'GatewayOutlined',
                'FunctionOutlined',
                'IssuesCloseOutlined',
                'ShakeOutlined',
                'SelectOutlined',
                'SendOutlined',
                'ScanOutlined',
                'TransactionOutlined',
                'OneToOneOutlined',
                'DeliveredProcedureOutlined',
                'RestOutlined',
                'RetweetOutlined',
                'SignatureOutlined',
                'SisternodeOutlined',
                'SkinOutlined',
                'SelectOutlined',
            ]
        }
    ]
}